# Setup
name:                Bootadmin
title:               Bootadmin
tagline:             Bootstrapping made simple.
author:              Sazzad Hossain
author_email:        sazzad@beeback.io
url:                 http://bootadmin.org
baseurl:             ''
permalink:           pretty
exclude:             [README.markdown]
analytics_id:        "UA-104952515-1"

# SEO information
seo:
    description: "Bootadmin is an open source bootstrap admin panel."
    keywords: "bootstrap, admin, theme, panel, administration, material"

# Owner/author information
owner:
    name:           Bootadmin
    avatar:         logo.png
    bio:            "Bootadmin is an open source bootstrap admin panel."
    email:          sazzad@beeback.io
    twitter:        iamshipon1988
    github:         iamshipon1988
    instagram:      comingsoon
    location:       "New York, NY"


# Custom vars
version:             0.1.0
github:
  repo:


# Plugins
plugins:
- jekyll-sitemap
